name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - run: ls -l target/release
    - run: ls -l target
    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: gensearchkey
        path: target/release/searchkeys
